# Generated by Django 3.1.2 on 2020-11-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
