# Generated by Django 3.1.2 on 2020-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_auto_20201106_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=60)),
                ('direccion', models.TextField()),
                ('correo', models.TextField()),
                ('telefono', models.TextField()),
                ('fecha_ing', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
