# Generated by Django 3.1.2 on 2020-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_datosper'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosper',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
