# Generated by Django 3.1.2 on 2020-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_datosper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosper',
            name='certificado',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='datosper',
            name='profesion',
            field=models.CharField(default='Lcdo en Informatica', max_length=250),
        ),
    ]
