# Generated by Django 3.1.2 on 2020-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_auto_20201107_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosper',
            name='certificado',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='datosper',
            name='profesion',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
