# Generated by Django 3.1.2 on 2020-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_auto_20201108_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='ZZZZZ', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='ZZZZZ', max_length=150),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(default='ZZZZZ', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='ZZZZZ', max_length=250),
        ),
    ]
