# Generated by Django 3.1.2 on 2020-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='URL_amigable')),
                ('visible', models.BooleanField(verbose_name='visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado_el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado_el')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
    ]
