# Generated by Django 3.1.2 on 2020-12-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201201_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
